name: Fork CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

concurrency:
  group: fork-ci-${{github.ref}}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - uses: DeterminateSystems/nix-installer-action@main

    - uses: DeterminateSystems/magic-nix-cache-action@main

    - name: nix build
      run: nix build .#default --print-build-logs
